// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/user.proto at 77:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * Represents a request of authentication
 */
public final class AuthRequest extends Message<AuthRequest, AuthRequest.Builder> {
  public static final ProtoAdapter<AuthRequest> ADAPTER = new ProtoAdapter_AuthRequest();

  private static final long serialVersionUID = 0L;

  public static final AuthProvider DEFAULT_PROVIDER = AuthProvider.TWITTER;

  public static final String DEFAULT_ACCESSTOKEN = "";

  public static final String DEFAULT_ACCESSTOKENSECRET = "";

  public static final String DEFAULT_DEVICEID = "";

  /**
   * / Provider name
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.AuthProvider#ADAPTER"
  )
  public final AuthProvider provider;

  /**
   * / Access token from provider
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String accessToken;

  /**
   * / Access token secret from provider
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String accessTokenSecret;

  /**
   * / Device ID
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String deviceId;

  public AuthRequest(AuthProvider provider, String accessToken, String accessTokenSecret, String deviceId) {
    this(provider, accessToken, accessTokenSecret, deviceId, ByteString.EMPTY);
  }

  public AuthRequest(AuthProvider provider, String accessToken, String accessTokenSecret, String deviceId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.provider = provider;
    this.accessToken = accessToken;
    this.accessTokenSecret = accessTokenSecret;
    this.deviceId = deviceId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.provider = provider;
    builder.accessToken = accessToken;
    builder.accessTokenSecret = accessTokenSecret;
    builder.deviceId = deviceId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AuthRequest)) return false;
    AuthRequest o = (AuthRequest) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(provider, o.provider)
        && Internal.equals(accessToken, o.accessToken)
        && Internal.equals(accessTokenSecret, o.accessTokenSecret)
        && Internal.equals(deviceId, o.deviceId);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (provider != null ? provider.hashCode() : 0);
      result = result * 37 + (accessToken != null ? accessToken.hashCode() : 0);
      result = result * 37 + (accessTokenSecret != null ? accessTokenSecret.hashCode() : 0);
      result = result * 37 + (deviceId != null ? deviceId.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (provider != null) builder.append(", provider=").append(provider);
    if (accessToken != null) builder.append(", accessToken=").append(accessToken);
    if (accessTokenSecret != null) builder.append(", accessTokenSecret=").append(accessTokenSecret);
    if (deviceId != null) builder.append(", deviceId=").append(deviceId);
    return builder.replace(0, 2, "AuthRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AuthRequest, Builder> {
    public AuthProvider provider;

    public String accessToken;

    public String accessTokenSecret;

    public String deviceId;

    public Builder() {
    }

    /**
     * / Provider name
     */
    public Builder provider(AuthProvider provider) {
      this.provider = provider;
      return this;
    }

    /**
     * / Access token from provider
     */
    public Builder accessToken(String accessToken) {
      this.accessToken = accessToken;
      return this;
    }

    /**
     * / Access token secret from provider
     */
    public Builder accessTokenSecret(String accessTokenSecret) {
      this.accessTokenSecret = accessTokenSecret;
      return this;
    }

    /**
     * / Device ID
     */
    public Builder deviceId(String deviceId) {
      this.deviceId = deviceId;
      return this;
    }

    @Override
    public AuthRequest build() {
      return new AuthRequest(provider, accessToken, accessTokenSecret, deviceId, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AuthRequest extends ProtoAdapter<AuthRequest> {
    ProtoAdapter_AuthRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, AuthRequest.class);
    }

    @Override
    public int encodedSize(AuthRequest value) {
      return (value.provider != null ? AuthProvider.ADAPTER.encodedSizeWithTag(1, value.provider) : 0)
          + (value.accessToken != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.accessToken) : 0)
          + (value.accessTokenSecret != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.accessTokenSecret) : 0)
          + (value.deviceId != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.deviceId) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AuthRequest value) throws IOException {
      if (value.provider != null) AuthProvider.ADAPTER.encodeWithTag(writer, 1, value.provider);
      if (value.accessToken != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.accessToken);
      if (value.accessTokenSecret != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.accessTokenSecret);
      if (value.deviceId != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.deviceId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AuthRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: {
            try {
              builder.provider(AuthProvider.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 2: builder.accessToken(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.accessTokenSecret(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.deviceId(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AuthRequest redact(AuthRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
