// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/broadcast_slots.proto at 64:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class BroadcastSlotStats extends Message<BroadcastSlotStats, BroadcastSlotStats.Builder> {
  public static final ProtoAdapter<BroadcastSlotStats> ADAPTER = new ProtoAdapter_BroadcastSlotStats();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_VIEW = 0L;

  public static final Long DEFAULT_COMMENT = 0L;

  /**
   * / 視聴数
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long view;

  /**
   * / コメント数
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long comment;

  public BroadcastSlotStats(Long view, Long comment) {
    this(view, comment, ByteString.EMPTY);
  }

  public BroadcastSlotStats(Long view, Long comment, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.view = view;
    this.comment = comment;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.view = view;
    builder.comment = comment;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BroadcastSlotStats)) return false;
    BroadcastSlotStats o = (BroadcastSlotStats) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(view, o.view)
        && Internal.equals(comment, o.comment);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (view != null ? view.hashCode() : 0);
      result = result * 37 + (comment != null ? comment.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (view != null) builder.append(", view=").append(view);
    if (comment != null) builder.append(", comment=").append(comment);
    return builder.replace(0, 2, "BroadcastSlotStats{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<BroadcastSlotStats, Builder> {
    public Long view;

    public Long comment;

    public Builder() {
    }

    /**
     * / 視聴数
     */
    public Builder view(Long view) {
      this.view = view;
      return this;
    }

    /**
     * / コメント数
     */
    public Builder comment(Long comment) {
      this.comment = comment;
      return this;
    }

    @Override
    public BroadcastSlotStats build() {
      return new BroadcastSlotStats(view, comment, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_BroadcastSlotStats extends ProtoAdapter<BroadcastSlotStats> {
    ProtoAdapter_BroadcastSlotStats() {
      super(FieldEncoding.LENGTH_DELIMITED, BroadcastSlotStats.class);
    }

    @Override
    public int encodedSize(BroadcastSlotStats value) {
      return (value.view != null ? ProtoAdapter.INT64.encodedSizeWithTag(1, value.view) : 0)
          + (value.comment != null ? ProtoAdapter.INT64.encodedSizeWithTag(2, value.comment) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, BroadcastSlotStats value) throws IOException {
      if (value.view != null) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.view);
      if (value.comment != null) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.comment);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public BroadcastSlotStats decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.view(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.comment(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public BroadcastSlotStats redact(BroadcastSlotStats value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
