// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/media.proto at 79:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / チャンネル配信情報
 */
public final class ChannelMediaStatus extends Message<ChannelMediaStatus, ChannelMediaStatus.Builder> {
  public static final ProtoAdapter<ChannelMediaStatus> ADAPTER = new ProtoAdapter_ChannelMediaStatus();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_DASHISOFF = false;

  /**
   * / MPEG-DASH ISOFF 配信可能チャンネル
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean dashISOFF;

  public ChannelMediaStatus(Boolean dashISOFF) {
    this(dashISOFF, ByteString.EMPTY);
  }

  public ChannelMediaStatus(Boolean dashISOFF, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.dashISOFF = dashISOFF;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.dashISOFF = dashISOFF;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ChannelMediaStatus)) return false;
    ChannelMediaStatus o = (ChannelMediaStatus) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(dashISOFF, o.dashISOFF);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (dashISOFF != null ? dashISOFF.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (dashISOFF != null) builder.append(", dashISOFF=").append(dashISOFF);
    return builder.replace(0, 2, "ChannelMediaStatus{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<ChannelMediaStatus, Builder> {
    public Boolean dashISOFF;

    public Builder() {
    }

    /**
     * / MPEG-DASH ISOFF 配信可能チャンネル
     */
    public Builder dashISOFF(Boolean dashISOFF) {
      this.dashISOFF = dashISOFF;
      return this;
    }

    @Override
    public ChannelMediaStatus build() {
      return new ChannelMediaStatus(dashISOFF, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_ChannelMediaStatus extends ProtoAdapter<ChannelMediaStatus> {
    ProtoAdapter_ChannelMediaStatus() {
      super(FieldEncoding.LENGTH_DELIMITED, ChannelMediaStatus.class);
    }

    @Override
    public int encodedSize(ChannelMediaStatus value) {
      return (value.dashISOFF != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.dashISOFF) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, ChannelMediaStatus value) throws IOException {
      if (value.dashISOFF != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.dashISOFF);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public ChannelMediaStatus decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.dashISOFF(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public ChannelMediaStatus redact(ChannelMediaStatus value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
