// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/download.proto at 11:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireEnum;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * /ダウンロード検証情報
 */
public final class DownloadValidation extends Message<DownloadValidation, DownloadValidation.Builder> {
  public static final ProtoAdapter<DownloadValidation> ADAPTER = new ProtoAdapter_DownloadValidation();

  private static final long serialVersionUID = 0L;

  public static final Code DEFAULT_CODE = Code.ENABLE;

  public static final String DEFAULT_TOKEN = "";

  public static final String DEFAULT_HLS = "";

  public static final String DEFAULT_DASH = "";

  /**
   * /検証結果コード
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.DownloadValidation$Code#ADAPTER"
  )
  public final Code code;

  /**
   * /ダウンロードトークン
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String token;

  /**
   * /HLSマスタープレイリスト
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String hls;

  /**
   * /DASH MPD
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String dash;

  public DownloadValidation(Code code, String token, String hls, String dash) {
    this(code, token, hls, dash, ByteString.EMPTY);
  }

  public DownloadValidation(Code code, String token, String hls, String dash, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.code = code;
    this.token = token;
    this.hls = hls;
    this.dash = dash;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.code = code;
    builder.token = token;
    builder.hls = hls;
    builder.dash = dash;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DownloadValidation)) return false;
    DownloadValidation o = (DownloadValidation) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(code, o.code)
        && Internal.equals(token, o.token)
        && Internal.equals(hls, o.hls)
        && Internal.equals(dash, o.dash);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (code != null ? code.hashCode() : 0);
      result = result * 37 + (token != null ? token.hashCode() : 0);
      result = result * 37 + (hls != null ? hls.hashCode() : 0);
      result = result * 37 + (dash != null ? dash.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (code != null) builder.append(", code=").append(code);
    if (token != null) builder.append(", token=").append(token);
    if (hls != null) builder.append(", hls=").append(hls);
    if (dash != null) builder.append(", dash=").append(dash);
    return builder.replace(0, 2, "DownloadValidation{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<DownloadValidation, Builder> {
    public Code code;

    public String token;

    public String hls;

    public String dash;

    public Builder() {
    }

    /**
     * /検証結果コード
     */
    public Builder code(Code code) {
      this.code = code;
      return this;
    }

    /**
     * /ダウンロードトークン
     */
    public Builder token(String token) {
      this.token = token;
      return this;
    }

    /**
     * /HLSマスタープレイリスト
     */
    public Builder hls(String hls) {
      this.hls = hls;
      return this;
    }

    /**
     * /DASH MPD
     */
    public Builder dash(String dash) {
      this.dash = dash;
      return this;
    }

    @Override
    public DownloadValidation build() {
      return new DownloadValidation(code, token, hls, dash, buildUnknownFields());
    }
  }

  public enum Code implements WireEnum {
    /**
     * / ダウンロード可能
     */
    ENABLE(0),

    /**
     * / タイムシフト再生期限切れ
     */
    OVER_TIMESHIFT(1),

    /**
     * / 公開期限切れ
     */
    OVER_PUBLISHED(2),

    /**
     * / ダウンロードフラグOFF
     */
    DL_FLAG_OFF(3),

    /**
     * / バージョン変更
     */
    VERSION_CHANGED(4),

    /**
     * / プレミアムプラン未加入
     */
    NOT_PREMIUM(5),

    /**
     * / コンテンツ保持時間切れ
     */
    OVER_RETENTION(6);

    public static final ProtoAdapter<Code> ADAPTER = ProtoAdapter.newEnumAdapter(Code.class);

    private final int value;

    Code(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static Code fromValue(int value) {
      switch (value) {
        case 0: return ENABLE;
        case 1: return OVER_TIMESHIFT;
        case 2: return OVER_PUBLISHED;
        case 3: return DL_FLAG_OFF;
        case 4: return VERSION_CHANGED;
        case 5: return NOT_PREMIUM;
        case 6: return OVER_RETENTION;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }
  }

  private static final class ProtoAdapter_DownloadValidation extends ProtoAdapter<DownloadValidation> {
    ProtoAdapter_DownloadValidation() {
      super(FieldEncoding.LENGTH_DELIMITED, DownloadValidation.class);
    }

    @Override
    public int encodedSize(DownloadValidation value) {
      return (value.code != null ? Code.ADAPTER.encodedSizeWithTag(1, value.code) : 0)
          + (value.token != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.token) : 0)
          + (value.hls != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.hls) : 0)
          + (value.dash != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.dash) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, DownloadValidation value) throws IOException {
      if (value.code != null) Code.ADAPTER.encodeWithTag(writer, 1, value.code);
      if (value.token != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.token);
      if (value.hls != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.hls);
      if (value.dash != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.dash);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public DownloadValidation decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: {
            try {
              builder.code(Code.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 2: builder.token(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.hls(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.dash(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public DownloadValidation redact(DownloadValidation value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
