// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/firebase.proto at 12:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / FirebaseRegisterRequest represents a firebae device.
 */
public final class FirebaseRegisterRequest extends Message<FirebaseRegisterRequest, FirebaseRegisterRequest.Builder> {
  public static final ProtoAdapter<FirebaseRegisterRequest> ADAPTER = new ProtoAdapter_FirebaseRegisterRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_REGISTRATIONID = "";

  /**
   * / Registration id.
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String registrationId;

  public FirebaseRegisterRequest(String registrationId) {
    this(registrationId, ByteString.EMPTY);
  }

  public FirebaseRegisterRequest(String registrationId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.registrationId = registrationId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.registrationId = registrationId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FirebaseRegisterRequest)) return false;
    FirebaseRegisterRequest o = (FirebaseRegisterRequest) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(registrationId, o.registrationId);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (registrationId != null ? registrationId.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (registrationId != null) builder.append(", registrationId=").append(registrationId);
    return builder.replace(0, 2, "FirebaseRegisterRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<FirebaseRegisterRequest, Builder> {
    public String registrationId;

    public Builder() {
    }

    /**
     * / Registration id.
     */
    public Builder registrationId(String registrationId) {
      this.registrationId = registrationId;
      return this;
    }

    @Override
    public FirebaseRegisterRequest build() {
      return new FirebaseRegisterRequest(registrationId, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_FirebaseRegisterRequest extends ProtoAdapter<FirebaseRegisterRequest> {
    ProtoAdapter_FirebaseRegisterRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, FirebaseRegisterRequest.class);
    }

    @Override
    public int encodedSize(FirebaseRegisterRequest value) {
      return (value.registrationId != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.registrationId) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, FirebaseRegisterRequest value) throws IOException {
      if (value.registrationId != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.registrationId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public FirebaseRegisterRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.registrationId(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public FirebaseRegisterRequest redact(FirebaseRegisterRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
