// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/broadcast_slots.proto at 98:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetBroadcastSlotResponse extends Message<GetBroadcastSlotResponse, GetBroadcastSlotResponse.Builder> {
  public static final ProtoAdapter<GetBroadcastSlotResponse> ADAPTER = new ProtoAdapter_GetBroadcastSlotResponse();

  private static final long serialVersionUID = 0L;

  /**
   * / 放送中の放送枠情報
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.BroadcastSlot#ADAPTER"
  )
  public final BroadcastSlot slot;

  public GetBroadcastSlotResponse(BroadcastSlot slot) {
    this(slot, ByteString.EMPTY);
  }

  public GetBroadcastSlotResponse(BroadcastSlot slot, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.slot = slot;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.slot = slot;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetBroadcastSlotResponse)) return false;
    GetBroadcastSlotResponse o = (GetBroadcastSlotResponse) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(slot, o.slot);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (slot != null ? slot.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (slot != null) builder.append(", slot=").append(slot);
    return builder.replace(0, 2, "GetBroadcastSlotResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetBroadcastSlotResponse, Builder> {
    public BroadcastSlot slot;

    public Builder() {
    }

    /**
     * / 放送中の放送枠情報
     */
    public Builder slot(BroadcastSlot slot) {
      this.slot = slot;
      return this;
    }

    @Override
    public GetBroadcastSlotResponse build() {
      return new GetBroadcastSlotResponse(slot, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetBroadcastSlotResponse extends ProtoAdapter<GetBroadcastSlotResponse> {
    ProtoAdapter_GetBroadcastSlotResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetBroadcastSlotResponse.class);
    }

    @Override
    public int encodedSize(GetBroadcastSlotResponse value) {
      return (value.slot != null ? BroadcastSlot.ADAPTER.encodedSizeWithTag(1, value.slot) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetBroadcastSlotResponse value) throws IOException {
      if (value.slot != null) BroadcastSlot.ADAPTER.encodeWithTag(writer, 1, value.slot);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetBroadcastSlotResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.slot(BroadcastSlot.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetBroadcastSlotResponse redact(GetBroadcastSlotResponse value) {
      Builder builder = value.newBuilder();
      if (builder.slot != null) builder.slot = BroadcastSlot.ADAPTER.redact(builder.slot);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
