// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/faq.proto at 27:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / GetFAQResponse represents a response of getting FAQ.
 */
public final class GetFAQResponse extends Message<GetFAQResponse, GetFAQResponse.Builder> {
  public static final ProtoAdapter<GetFAQResponse> ADAPTER = new ProtoAdapter_GetFAQResponse();

  private static final long serialVersionUID = 0L;

  /**
   * / frequently asked question
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.FAQ#ADAPTER"
  )
  public final FAQ faq;

  public GetFAQResponse(FAQ faq) {
    this(faq, ByteString.EMPTY);
  }

  public GetFAQResponse(FAQ faq, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.faq = faq;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.faq = faq;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetFAQResponse)) return false;
    GetFAQResponse o = (GetFAQResponse) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(faq, o.faq);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (faq != null ? faq.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (faq != null) builder.append(", faq=").append(faq);
    return builder.replace(0, 2, "GetFAQResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetFAQResponse, Builder> {
    public FAQ faq;

    public Builder() {
    }

    /**
     * / frequently asked question
     */
    public Builder faq(FAQ faq) {
      this.faq = faq;
      return this;
    }

    @Override
    public GetFAQResponse build() {
      return new GetFAQResponse(faq, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetFAQResponse extends ProtoAdapter<GetFAQResponse> {
    ProtoAdapter_GetFAQResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetFAQResponse.class);
    }

    @Override
    public int encodedSize(GetFAQResponse value) {
      return (value.faq != null ? FAQ.ADAPTER.encodedSizeWithTag(1, value.faq) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetFAQResponse value) throws IOException {
      if (value.faq != null) FAQ.ADAPTER.encodeWithTag(writer, 1, value.faq);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetFAQResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.faq(FAQ.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetFAQResponse redact(GetFAQResponse value) {
      Builder builder = value.newBuilder();
      if (builder.faq != null) builder.faq = FAQ.ADAPTER.redact(builder.faq);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
