// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/media.proto at 276:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * Represents a request to get slot audience response.
 */
public final class GetSlotAudienceResponse extends Message<GetSlotAudienceResponse, GetSlotAudienceResponse.Builder> {
  public static final ProtoAdapter<GetSlotAudienceResponse> ADAPTER = new ProtoAdapter_GetSlotAudienceResponse();

  private static final long serialVersionUID = 0L;

  /**
   * / SlotAudience slice
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.SlotAudience#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<SlotAudience> slotAudiences;

  public GetSlotAudienceResponse(List<SlotAudience> slotAudiences) {
    this(slotAudiences, ByteString.EMPTY);
  }

  public GetSlotAudienceResponse(List<SlotAudience> slotAudiences, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.slotAudiences = Internal.immutableCopyOf("slotAudiences", slotAudiences);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.slotAudiences = Internal.copyOf("slotAudiences", slotAudiences);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetSlotAudienceResponse)) return false;
    GetSlotAudienceResponse o = (GetSlotAudienceResponse) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(slotAudiences, o.slotAudiences);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (slotAudiences != null ? slotAudiences.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (slotAudiences != null) builder.append(", slotAudiences=").append(slotAudiences);
    return builder.replace(0, 2, "GetSlotAudienceResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetSlotAudienceResponse, Builder> {
    public List<SlotAudience> slotAudiences;

    public Builder() {
      slotAudiences = Internal.newMutableList();
    }

    /**
     * / SlotAudience slice
     */
    public Builder slotAudiences(List<SlotAudience> slotAudiences) {
      Internal.checkElementsNotNull(slotAudiences);
      this.slotAudiences = slotAudiences;
      return this;
    }

    @Override
    public GetSlotAudienceResponse build() {
      return new GetSlotAudienceResponse(slotAudiences, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetSlotAudienceResponse extends ProtoAdapter<GetSlotAudienceResponse> {
    ProtoAdapter_GetSlotAudienceResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetSlotAudienceResponse.class);
    }

    @Override
    public int encodedSize(GetSlotAudienceResponse value) {
      return SlotAudience.ADAPTER.asRepeated().encodedSizeWithTag(1, value.slotAudiences)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetSlotAudienceResponse value) throws IOException {
      if (value.slotAudiences != null) SlotAudience.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.slotAudiences);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetSlotAudienceResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.slotAudiences.add(SlotAudience.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetSlotAudienceResponse redact(GetSlotAudienceResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.slotAudiences, SlotAudience.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
