// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/viewing_reservation.proto at 25:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * / GetViewingReservationSlotsReponse represents a response of getting viewing reservation slots.
 */
public final class GetViewingReservationSlotsResponse extends Message<GetViewingReservationSlotsResponse, GetViewingReservationSlotsResponse.Builder> {
  public static final ProtoAdapter<GetViewingReservationSlotsResponse> ADAPTER = new ProtoAdapter_GetViewingReservationSlotsResponse();

  private static final long serialVersionUID = 0L;

  /**
   * / Slot list that have been reserved for viewing.
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.ViewingReservationSlot#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<ViewingReservationSlot> slots;

  /**
   * / The associated data set.
   */
  @WireField(
      tag = 10,
      adapter = "tv.abema.protos.DataSet#ADAPTER"
  )
  public final DataSet dataSet;

  public GetViewingReservationSlotsResponse(List<ViewingReservationSlot> slots, DataSet dataSet) {
    this(slots, dataSet, ByteString.EMPTY);
  }

  public GetViewingReservationSlotsResponse(List<ViewingReservationSlot> slots, DataSet dataSet, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.slots = Internal.immutableCopyOf("slots", slots);
    this.dataSet = dataSet;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.slots = Internal.copyOf("slots", slots);
    builder.dataSet = dataSet;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetViewingReservationSlotsResponse)) return false;
    GetViewingReservationSlotsResponse o = (GetViewingReservationSlotsResponse) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(slots, o.slots)
        && Internal.equals(dataSet, o.dataSet);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (slots != null ? slots.hashCode() : 1);
      result = result * 37 + (dataSet != null ? dataSet.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (slots != null) builder.append(", slots=").append(slots);
    if (dataSet != null) builder.append(", dataSet=").append(dataSet);
    return builder.replace(0, 2, "GetViewingReservationSlotsResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetViewingReservationSlotsResponse, Builder> {
    public List<ViewingReservationSlot> slots;

    public DataSet dataSet;

    public Builder() {
      slots = Internal.newMutableList();
    }

    /**
     * / Slot list that have been reserved for viewing.
     */
    public Builder slots(List<ViewingReservationSlot> slots) {
      Internal.checkElementsNotNull(slots);
      this.slots = slots;
      return this;
    }

    /**
     * / The associated data set.
     */
    public Builder dataSet(DataSet dataSet) {
      this.dataSet = dataSet;
      return this;
    }

    @Override
    public GetViewingReservationSlotsResponse build() {
      return new GetViewingReservationSlotsResponse(slots, dataSet, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetViewingReservationSlotsResponse extends ProtoAdapter<GetViewingReservationSlotsResponse> {
    ProtoAdapter_GetViewingReservationSlotsResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetViewingReservationSlotsResponse.class);
    }

    @Override
    public int encodedSize(GetViewingReservationSlotsResponse value) {
      return ViewingReservationSlot.ADAPTER.asRepeated().encodedSizeWithTag(1, value.slots)
          + (value.dataSet != null ? DataSet.ADAPTER.encodedSizeWithTag(10, value.dataSet) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetViewingReservationSlotsResponse value) throws IOException {
      if (value.slots != null) ViewingReservationSlot.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.slots);
      if (value.dataSet != null) DataSet.ADAPTER.encodeWithTag(writer, 10, value.dataSet);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetViewingReservationSlotsResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.slots.add(ViewingReservationSlot.ADAPTER.decode(reader)); break;
          case 10: builder.dataSet(DataSet.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetViewingReservationSlotsResponse redact(GetViewingReservationSlotsResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.slots, ViewingReservationSlot.ADAPTER);
      if (builder.dataSet != null) builder.dataSet = DataSet.ADAPTER.redact(builder.dataSet);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
