// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/video.proto at 144:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * ビデオシリーズにおける提案枠プログラムの一覧取得レスポンス
 */
public final class GetVideoSeriesSuggestedProgramsResponse extends Message<GetVideoSeriesSuggestedProgramsResponse, GetVideoSeriesSuggestedProgramsResponse.Builder> {
  public static final ProtoAdapter<GetVideoSeriesSuggestedProgramsResponse> ADAPTER = new ProtoAdapter_GetVideoSeriesSuggestedProgramsResponse();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.VideoSeriesSuggestedProgram#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<VideoSeriesSuggestedProgram> programs;

  public GetVideoSeriesSuggestedProgramsResponse(List<VideoSeriesSuggestedProgram> programs) {
    this(programs, ByteString.EMPTY);
  }

  public GetVideoSeriesSuggestedProgramsResponse(List<VideoSeriesSuggestedProgram> programs, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.programs = Internal.immutableCopyOf("programs", programs);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.programs = Internal.copyOf("programs", programs);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetVideoSeriesSuggestedProgramsResponse)) return false;
    GetVideoSeriesSuggestedProgramsResponse o = (GetVideoSeriesSuggestedProgramsResponse) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(programs, o.programs);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (programs != null ? programs.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (programs != null) builder.append(", programs=").append(programs);
    return builder.replace(0, 2, "GetVideoSeriesSuggestedProgramsResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetVideoSeriesSuggestedProgramsResponse, Builder> {
    public List<VideoSeriesSuggestedProgram> programs;

    public Builder() {
      programs = Internal.newMutableList();
    }

    public Builder programs(List<VideoSeriesSuggestedProgram> programs) {
      Internal.checkElementsNotNull(programs);
      this.programs = programs;
      return this;
    }

    @Override
    public GetVideoSeriesSuggestedProgramsResponse build() {
      return new GetVideoSeriesSuggestedProgramsResponse(programs, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetVideoSeriesSuggestedProgramsResponse extends ProtoAdapter<GetVideoSeriesSuggestedProgramsResponse> {
    ProtoAdapter_GetVideoSeriesSuggestedProgramsResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetVideoSeriesSuggestedProgramsResponse.class);
    }

    @Override
    public int encodedSize(GetVideoSeriesSuggestedProgramsResponse value) {
      return VideoSeriesSuggestedProgram.ADAPTER.asRepeated().encodedSizeWithTag(1, value.programs)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetVideoSeriesSuggestedProgramsResponse value) throws IOException {
      if (value.programs != null) VideoSeriesSuggestedProgram.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.programs);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetVideoSeriesSuggestedProgramsResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.programs.add(VideoSeriesSuggestedProgram.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetVideoSeriesSuggestedProgramsResponse redact(GetVideoSeriesSuggestedProgramsResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.programs, VideoSeriesSuggestedProgram.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
