// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/track.proto at 204:1
package tv.abema.protos;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum MineShareType implements WireEnum {
  share_feed(0),

  share_fullscreen(1),

  share_detail_info(2),

  share_other(3);

  public static final ProtoAdapter<MineShareType> ADAPTER = ProtoAdapter.newEnumAdapter(MineShareType.class);

  private final int value;

  MineShareType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static MineShareType fromValue(int value) {
    switch (value) {
      case 0: return share_feed;
      case 1: return share_fullscreen;
      case 2: return share_detail_info;
      case 3: return share_other;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
