// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/track.proto at 304:1
package tv.abema.protos;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum MineFillerType implements WireEnum {
  filler_normal(0),

  filler_countdown(1),

  filler_logo(2),

  filler_moment(3);

  public static final ProtoAdapter<MineFillerType> ADAPTER = ProtoAdapter.newEnumAdapter(MineFillerType.class);

  private final int value;

  MineFillerType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static MineFillerType fromValue(int value) {
    switch (value) {
      case 0: return filler_normal;
      case 1: return filler_countdown;
      case 2: return filler_logo;
      case 3: return filler_moment;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
