// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/media.proto at 304:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * Represents a request to post a slot reservation.
 */
public final class PostSlotReservationRequest extends Message<PostSlotReservationRequest, PostSlotReservationRequest.Builder> {
  public static final ProtoAdapter<PostSlotReservationRequest> ADAPTER = new ProtoAdapter_PostSlotReservationRequest();

  private static final long serialVersionUID = 0L;

  /**
   * / 放送枠予約登録リスト
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.SlotReservation#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<SlotReservation> slotReservations;

  public PostSlotReservationRequest(List<SlotReservation> slotReservations) {
    this(slotReservations, ByteString.EMPTY);
  }

  public PostSlotReservationRequest(List<SlotReservation> slotReservations, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.slotReservations = Internal.immutableCopyOf("slotReservations", slotReservations);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.slotReservations = Internal.copyOf("slotReservations", slotReservations);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PostSlotReservationRequest)) return false;
    PostSlotReservationRequest o = (PostSlotReservationRequest) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(slotReservations, o.slotReservations);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (slotReservations != null ? slotReservations.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (slotReservations != null) builder.append(", slotReservations=").append(slotReservations);
    return builder.replace(0, 2, "PostSlotReservationRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PostSlotReservationRequest, Builder> {
    public List<SlotReservation> slotReservations;

    public Builder() {
      slotReservations = Internal.newMutableList();
    }

    /**
     * / 放送枠予約登録リスト
     */
    public Builder slotReservations(List<SlotReservation> slotReservations) {
      Internal.checkElementsNotNull(slotReservations);
      this.slotReservations = slotReservations;
      return this;
    }

    @Override
    public PostSlotReservationRequest build() {
      return new PostSlotReservationRequest(slotReservations, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PostSlotReservationRequest extends ProtoAdapter<PostSlotReservationRequest> {
    ProtoAdapter_PostSlotReservationRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, PostSlotReservationRequest.class);
    }

    @Override
    public int encodedSize(PostSlotReservationRequest value) {
      return SlotReservation.ADAPTER.asRepeated().encodedSizeWithTag(1, value.slotReservations)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PostSlotReservationRequest value) throws IOException {
      if (value.slotReservations != null) SlotReservation.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.slotReservations);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PostSlotReservationRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.slotReservations.add(SlotReservation.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PostSlotReservationRequest redact(PostSlotReservationRequest value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.slotReservations, SlotReservation.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
