// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/video.proto at 183:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * /ダウンロードビデオエピソード
 */
public final class ProgramDownload extends Message<ProgramDownload, ProgramDownload.Builder> {
  public static final ProtoAdapter<ProgramDownload> ADAPTER = new ProtoAdapter_ProgramDownload();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_ENABLE = false;

  /**
   * /ダウンロード可否
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean enable;

  public ProgramDownload(Boolean enable) {
    this(enable, ByteString.EMPTY);
  }

  public ProgramDownload(Boolean enable, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.enable = enable;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.enable = enable;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProgramDownload)) return false;
    ProgramDownload o = (ProgramDownload) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(enable, o.enable);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (enable != null ? enable.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (enable != null) builder.append(", enable=").append(enable);
    return builder.replace(0, 2, "ProgramDownload{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<ProgramDownload, Builder> {
    public Boolean enable;

    public Builder() {
    }

    /**
     * /ダウンロード可否
     */
    public Builder enable(Boolean enable) {
      this.enable = enable;
      return this;
    }

    @Override
    public ProgramDownload build() {
      return new ProgramDownload(enable, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_ProgramDownload extends ProtoAdapter<ProgramDownload> {
    ProtoAdapter_ProgramDownload() {
      super(FieldEncoding.LENGTH_DELIMITED, ProgramDownload.class);
    }

    @Override
    public int encodedSize(ProgramDownload value) {
      return (value.enable != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.enable) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, ProgramDownload value) throws IOException {
      if (value.enable != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.enable);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public ProgramDownload decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.enable(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public ProgramDownload redact(ProgramDownload value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
