// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/media.proto at 202:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / 番組エピソード情報
 */
public final class ProgramEpisode extends Message<ProgramEpisode, ProgramEpisode.Builder> {
  public static final ProtoAdapter<ProgramEpisode> ADAPTER = new ProtoAdapter_ProgramEpisode();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NAME = "";

  public static final Integer DEFAULT_SEQUENCE = 0;

  public static final String DEFAULT_TITLE = "";

  public static final String DEFAULT_OVERVIEW = "";

  public static final String DEFAULT_CONTENT = "";

  /**
   * / エピソード名称 ex) 第一話
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String name;

  /**
   * / エピソード番号 ex) 1
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer sequence;

  /**
   * / エピソードタイトル ex) ドラえもん登場
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String title;

  /**
   * / エピソード概要
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String overview;

  /**
   * / エピソード詳細
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String content;

  public ProgramEpisode(String name, Integer sequence, String title, String overview, String content) {
    this(name, sequence, title, overview, content, ByteString.EMPTY);
  }

  public ProgramEpisode(String name, Integer sequence, String title, String overview, String content, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.name = name;
    this.sequence = sequence;
    this.title = title;
    this.overview = overview;
    this.content = content;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.name = name;
    builder.sequence = sequence;
    builder.title = title;
    builder.overview = overview;
    builder.content = content;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProgramEpisode)) return false;
    ProgramEpisode o = (ProgramEpisode) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(name, o.name)
        && Internal.equals(sequence, o.sequence)
        && Internal.equals(title, o.title)
        && Internal.equals(overview, o.overview)
        && Internal.equals(content, o.content);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (sequence != null ? sequence.hashCode() : 0);
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (overview != null ? overview.hashCode() : 0);
      result = result * 37 + (content != null ? content.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (name != null) builder.append(", name=").append(name);
    if (sequence != null) builder.append(", sequence=").append(sequence);
    if (title != null) builder.append(", title=").append(title);
    if (overview != null) builder.append(", overview=").append(overview);
    if (content != null) builder.append(", content=").append(content);
    return builder.replace(0, 2, "ProgramEpisode{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<ProgramEpisode, Builder> {
    public String name;

    public Integer sequence;

    public String title;

    public String overview;

    public String content;

    public Builder() {
    }

    /**
     * / エピソード名称 ex) 第一話
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * / エピソード番号 ex) 1
     */
    public Builder sequence(Integer sequence) {
      this.sequence = sequence;
      return this;
    }

    /**
     * / エピソードタイトル ex) ドラえもん登場
     */
    public Builder title(String title) {
      this.title = title;
      return this;
    }

    /**
     * / エピソード概要
     */
    public Builder overview(String overview) {
      this.overview = overview;
      return this;
    }

    /**
     * / エピソード詳細
     */
    public Builder content(String content) {
      this.content = content;
      return this;
    }

    @Override
    public ProgramEpisode build() {
      return new ProgramEpisode(name, sequence, title, overview, content, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_ProgramEpisode extends ProtoAdapter<ProgramEpisode> {
    ProtoAdapter_ProgramEpisode() {
      super(FieldEncoding.LENGTH_DELIMITED, ProgramEpisode.class);
    }

    @Override
    public int encodedSize(ProgramEpisode value) {
      return (value.name != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.name) : 0)
          + (value.sequence != null ? ProtoAdapter.INT32.encodedSizeWithTag(2, value.sequence) : 0)
          + (value.title != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.title) : 0)
          + (value.overview != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.overview) : 0)
          + (value.content != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.content) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, ProgramEpisode value) throws IOException {
      if (value.name != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name);
      if (value.sequence != null) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.sequence);
      if (value.title != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.title);
      if (value.overview != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.overview);
      if (value.content != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.content);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public ProgramEpisode decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.sequence(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.title(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.overview(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.content(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public ProgramEpisode redact(ProgramEpisode value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
