// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/subscription.proto at 17:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / Google月額課金情報登録 request
 */
public final class RegisterGoogleSubscriptionRequest extends Message<RegisterGoogleSubscriptionRequest, RegisterGoogleSubscriptionRequest.Builder> {
  public static final ProtoAdapter<RegisterGoogleSubscriptionRequest> ADAPTER = new ProtoAdapter_RegisterGoogleSubscriptionRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_PURCHASEDATA = "";

  public static final String DEFAULT_SIGNATURE = "";

  /**
   * / 購入データ(INAPP_PURCHASE_DATA)のJSON
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String purchaseData;

  /**
   * / シグネチャ(INAPP_DATA_SIGNATURE)
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String signature;

  public RegisterGoogleSubscriptionRequest(String purchaseData, String signature) {
    this(purchaseData, signature, ByteString.EMPTY);
  }

  public RegisterGoogleSubscriptionRequest(String purchaseData, String signature, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.purchaseData = purchaseData;
    this.signature = signature;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.purchaseData = purchaseData;
    builder.signature = signature;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RegisterGoogleSubscriptionRequest)) return false;
    RegisterGoogleSubscriptionRequest o = (RegisterGoogleSubscriptionRequest) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(purchaseData, o.purchaseData)
        && Internal.equals(signature, o.signature);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (purchaseData != null ? purchaseData.hashCode() : 0);
      result = result * 37 + (signature != null ? signature.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (purchaseData != null) builder.append(", purchaseData=").append(purchaseData);
    if (signature != null) builder.append(", signature=").append(signature);
    return builder.replace(0, 2, "RegisterGoogleSubscriptionRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RegisterGoogleSubscriptionRequest, Builder> {
    public String purchaseData;

    public String signature;

    public Builder() {
    }

    /**
     * / 購入データ(INAPP_PURCHASE_DATA)のJSON
     */
    public Builder purchaseData(String purchaseData) {
      this.purchaseData = purchaseData;
      return this;
    }

    /**
     * / シグネチャ(INAPP_DATA_SIGNATURE)
     */
    public Builder signature(String signature) {
      this.signature = signature;
      return this;
    }

    @Override
    public RegisterGoogleSubscriptionRequest build() {
      return new RegisterGoogleSubscriptionRequest(purchaseData, signature, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RegisterGoogleSubscriptionRequest extends ProtoAdapter<RegisterGoogleSubscriptionRequest> {
    ProtoAdapter_RegisterGoogleSubscriptionRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, RegisterGoogleSubscriptionRequest.class);
    }

    @Override
    public int encodedSize(RegisterGoogleSubscriptionRequest value) {
      return (value.purchaseData != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.purchaseData) : 0)
          + (value.signature != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.signature) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, RegisterGoogleSubscriptionRequest value) throws IOException {
      if (value.purchaseData != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.purchaseData);
      if (value.signature != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.signature);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RegisterGoogleSubscriptionRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.purchaseData(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.signature(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public RegisterGoogleSubscriptionRequest redact(RegisterGoogleSubscriptionRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
