// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/user.proto at 147:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / Amazon復元 request
 */
public final class RestoreAmazonRequest extends Message<RestoreAmazonRequest, RestoreAmazonRequest.Builder> {
  public static final ProtoAdapter<RestoreAmazonRequest> ADAPTER = new ProtoAdapter_RestoreAmazonRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_RECEIPTID = "";

  public static final String DEFAULT_AMAZONUSERID = "";

  /**
   * / AmazonレシートID
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String receiptId;

  /**
   * / Amazon UserID
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String amazonUserId;

  public RestoreAmazonRequest(String receiptId, String amazonUserId) {
    this(receiptId, amazonUserId, ByteString.EMPTY);
  }

  public RestoreAmazonRequest(String receiptId, String amazonUserId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.receiptId = receiptId;
    this.amazonUserId = amazonUserId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.receiptId = receiptId;
    builder.amazonUserId = amazonUserId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RestoreAmazonRequest)) return false;
    RestoreAmazonRequest o = (RestoreAmazonRequest) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(receiptId, o.receiptId)
        && Internal.equals(amazonUserId, o.amazonUserId);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (receiptId != null ? receiptId.hashCode() : 0);
      result = result * 37 + (amazonUserId != null ? amazonUserId.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (receiptId != null) builder.append(", receiptId=").append(receiptId);
    if (amazonUserId != null) builder.append(", amazonUserId=").append(amazonUserId);
    return builder.replace(0, 2, "RestoreAmazonRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RestoreAmazonRequest, Builder> {
    public String receiptId;

    public String amazonUserId;

    public Builder() {
    }

    /**
     * / AmazonレシートID
     */
    public Builder receiptId(String receiptId) {
      this.receiptId = receiptId;
      return this;
    }

    /**
     * / Amazon UserID
     */
    public Builder amazonUserId(String amazonUserId) {
      this.amazonUserId = amazonUserId;
      return this;
    }

    @Override
    public RestoreAmazonRequest build() {
      return new RestoreAmazonRequest(receiptId, amazonUserId, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RestoreAmazonRequest extends ProtoAdapter<RestoreAmazonRequest> {
    ProtoAdapter_RestoreAmazonRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, RestoreAmazonRequest.class);
    }

    @Override
    public int encodedSize(RestoreAmazonRequest value) {
      return (value.receiptId != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.receiptId) : 0)
          + (value.amazonUserId != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.amazonUserId) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, RestoreAmazonRequest value) throws IOException {
      if (value.receiptId != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.receiptId);
      if (value.amazonUserId != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.amazonUserId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RestoreAmazonRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.receiptId(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.amazonUserId(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public RestoreAmazonRequest redact(RestoreAmazonRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
