// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/user.proto at 211:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / ワンタイムパスワードの設定 requrest
 */
public final class SetOneTimePasswordRequest extends Message<SetOneTimePasswordRequest, SetOneTimePasswordRequest.Builder> {
  public static final ProtoAdapter<SetOneTimePasswordRequest> ADAPTER = new ProtoAdapter_SetOneTimePasswordRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_PASSWORD = "";

  /**
   * / ワンタイムパスワード
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String password;

  public SetOneTimePasswordRequest(String password) {
    this(password, ByteString.EMPTY);
  }

  public SetOneTimePasswordRequest(String password, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.password = password;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.password = password;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SetOneTimePasswordRequest)) return false;
    SetOneTimePasswordRequest o = (SetOneTimePasswordRequest) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(password, o.password);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (password != null ? password.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (password != null) builder.append(", password=").append(password);
    return builder.replace(0, 2, "SetOneTimePasswordRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SetOneTimePasswordRequest, Builder> {
    public String password;

    public Builder() {
    }

    /**
     * / ワンタイムパスワード
     */
    public Builder password(String password) {
      this.password = password;
      return this;
    }

    @Override
    public SetOneTimePasswordRequest build() {
      return new SetOneTimePasswordRequest(password, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SetOneTimePasswordRequest extends ProtoAdapter<SetOneTimePasswordRequest> {
    ProtoAdapter_SetOneTimePasswordRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, SetOneTimePasswordRequest.class);
    }

    @Override
    public int encodedSize(SetOneTimePasswordRequest value) {
      return (value.password != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.password) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, SetOneTimePasswordRequest value) throws IOException {
      if (value.password != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.password);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SetOneTimePasswordRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.password(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public SetOneTimePasswordRequest redact(SetOneTimePasswordRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
