// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/media.proto at 269:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / 番組枠情報取得 response
 */
public final class SlotResponse extends Message<SlotResponse, SlotResponse.Builder> {
  public static final ProtoAdapter<SlotResponse> ADAPTER = new ProtoAdapter_SlotResponse();

  private static final long serialVersionUID = 0L;

  /**
   * / 枠情報
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.ScheduleSlot#ADAPTER"
  )
  public final ScheduleSlot slot;

  public SlotResponse(ScheduleSlot slot) {
    this(slot, ByteString.EMPTY);
  }

  public SlotResponse(ScheduleSlot slot, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.slot = slot;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.slot = slot;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SlotResponse)) return false;
    SlotResponse o = (SlotResponse) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(slot, o.slot);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (slot != null ? slot.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (slot != null) builder.append(", slot=").append(slot);
    return builder.replace(0, 2, "SlotResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SlotResponse, Builder> {
    public ScheduleSlot slot;

    public Builder() {
    }

    /**
     * / 枠情報
     */
    public Builder slot(ScheduleSlot slot) {
      this.slot = slot;
      return this;
    }

    @Override
    public SlotResponse build() {
      return new SlotResponse(slot, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SlotResponse extends ProtoAdapter<SlotResponse> {
    ProtoAdapter_SlotResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, SlotResponse.class);
    }

    @Override
    public int encodedSize(SlotResponse value) {
      return (value.slot != null ? ScheduleSlot.ADAPTER.encodedSizeWithTag(1, value.slot) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, SlotResponse value) throws IOException {
      if (value.slot != null) ScheduleSlot.ADAPTER.encodeWithTag(writer, 1, value.slot);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SlotResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.slot(ScheduleSlot.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public SlotResponse redact(SlotResponse value) {
      Builder builder = value.newBuilder();
      if (builder.slot != null) builder.slot = ScheduleSlot.ADAPTER.redact(builder.slot);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
