// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/subscription.proto at 66:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / キャリア決済月額課金登録のための注文開始 response
 */
public final class StartCarrierOrderResponse extends Message<StartCarrierOrderResponse, StartCarrierOrderResponse.Builder> {
  public static final ProtoAdapter<StartCarrierOrderResponse> ADAPTER = new ProtoAdapter_StartCarrierOrderResponse();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_ACCESSID = "";

  public static final String DEFAULT_TOKEN = "";

  public static final String DEFAULT_STARTURL = "";

  public static final Long DEFAULT_EXPIRE = 0L;

  /**
   * / アクセスID
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String accessId;

  /**
   * / トークン
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String token;

  /**
   * / 支払い手続き開始IFのURL
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String startUrl;

  /**
   * / 支払い期限日時(秒)
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long expire;

  public StartCarrierOrderResponse(String accessId, String token, String startUrl, Long expire) {
    this(accessId, token, startUrl, expire, ByteString.EMPTY);
  }

  public StartCarrierOrderResponse(String accessId, String token, String startUrl, Long expire, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.accessId = accessId;
    this.token = token;
    this.startUrl = startUrl;
    this.expire = expire;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.accessId = accessId;
    builder.token = token;
    builder.startUrl = startUrl;
    builder.expire = expire;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof StartCarrierOrderResponse)) return false;
    StartCarrierOrderResponse o = (StartCarrierOrderResponse) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(accessId, o.accessId)
        && Internal.equals(token, o.token)
        && Internal.equals(startUrl, o.startUrl)
        && Internal.equals(expire, o.expire);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (accessId != null ? accessId.hashCode() : 0);
      result = result * 37 + (token != null ? token.hashCode() : 0);
      result = result * 37 + (startUrl != null ? startUrl.hashCode() : 0);
      result = result * 37 + (expire != null ? expire.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (accessId != null) builder.append(", accessId=").append(accessId);
    if (token != null) builder.append(", token=").append(token);
    if (startUrl != null) builder.append(", startUrl=").append(startUrl);
    if (expire != null) builder.append(", expire=").append(expire);
    return builder.replace(0, 2, "StartCarrierOrderResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<StartCarrierOrderResponse, Builder> {
    public String accessId;

    public String token;

    public String startUrl;

    public Long expire;

    public Builder() {
    }

    /**
     * / アクセスID
     */
    public Builder accessId(String accessId) {
      this.accessId = accessId;
      return this;
    }

    /**
     * / トークン
     */
    public Builder token(String token) {
      this.token = token;
      return this;
    }

    /**
     * / 支払い手続き開始IFのURL
     */
    public Builder startUrl(String startUrl) {
      this.startUrl = startUrl;
      return this;
    }

    /**
     * / 支払い期限日時(秒)
     */
    public Builder expire(Long expire) {
      this.expire = expire;
      return this;
    }

    @Override
    public StartCarrierOrderResponse build() {
      return new StartCarrierOrderResponse(accessId, token, startUrl, expire, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_StartCarrierOrderResponse extends ProtoAdapter<StartCarrierOrderResponse> {
    ProtoAdapter_StartCarrierOrderResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, StartCarrierOrderResponse.class);
    }

    @Override
    public int encodedSize(StartCarrierOrderResponse value) {
      return (value.accessId != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.accessId) : 0)
          + (value.token != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.token) : 0)
          + (value.startUrl != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.startUrl) : 0)
          + (value.expire != null ? ProtoAdapter.INT64.encodedSizeWithTag(4, value.expire) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, StartCarrierOrderResponse value) throws IOException {
      if (value.accessId != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.accessId);
      if (value.token != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.token);
      if (value.startUrl != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.startUrl);
      if (value.expire != null) ProtoAdapter.INT64.encodeWithTag(writer, 4, value.expire);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public StartCarrierOrderResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.accessId(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.token(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.startUrl(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.expire(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public StartCarrierOrderResponse redact(StartCarrierOrderResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
