// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/video_feature.proto at 41:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * / ビデオビルボード
 */
public final class VideoBillboard extends Message<VideoBillboard, VideoBillboard.Builder> {
  public static final ProtoAdapter<VideoBillboard> ADAPTER = new ProtoAdapter_VideoBillboard();

  private static final long serialVersionUID = 0L;

  /**
   * / カード一覧
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.VideoCard#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<VideoCard> cards;

  public VideoBillboard(List<VideoCard> cards) {
    this(cards, ByteString.EMPTY);
  }

  public VideoBillboard(List<VideoCard> cards, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.cards = Internal.immutableCopyOf("cards", cards);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.cards = Internal.copyOf("cards", cards);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof VideoBillboard)) return false;
    VideoBillboard o = (VideoBillboard) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(cards, o.cards);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (cards != null ? cards.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (cards != null) builder.append(", cards=").append(cards);
    return builder.replace(0, 2, "VideoBillboard{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<VideoBillboard, Builder> {
    public List<VideoCard> cards;

    public Builder() {
      cards = Internal.newMutableList();
    }

    /**
     * / カード一覧
     */
    public Builder cards(List<VideoCard> cards) {
      Internal.checkElementsNotNull(cards);
      this.cards = cards;
      return this;
    }

    @Override
    public VideoBillboard build() {
      return new VideoBillboard(cards, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_VideoBillboard extends ProtoAdapter<VideoBillboard> {
    ProtoAdapter_VideoBillboard() {
      super(FieldEncoding.LENGTH_DELIMITED, VideoBillboard.class);
    }

    @Override
    public int encodedSize(VideoBillboard value) {
      return VideoCard.ADAPTER.asRepeated().encodedSizeWithTag(1, value.cards)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, VideoBillboard value) throws IOException {
      if (value.cards != null) VideoCard.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.cards);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public VideoBillboard decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.cards.add(VideoCard.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public VideoBillboard redact(VideoBillboard value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.cards, VideoCard.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
