// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/video.proto at 66:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / ビデオ番組ラベル
 */
public final class VideoProgramLabel extends Message<VideoProgramLabel, VideoProgramLabel.Builder> {
  public static final ProtoAdapter<VideoProgramLabel> ADAPTER = new ProtoAdapter_VideoProgramLabel();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_FREE = false;

  /**
   * / 無料
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean free;

  public VideoProgramLabel(Boolean free) {
    this(free, ByteString.EMPTY);
  }

  public VideoProgramLabel(Boolean free, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.free = free;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.free = free;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof VideoProgramLabel)) return false;
    VideoProgramLabel o = (VideoProgramLabel) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(free, o.free);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (free != null ? free.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (free != null) builder.append(", free=").append(free);
    return builder.replace(0, 2, "VideoProgramLabel{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<VideoProgramLabel, Builder> {
    public Boolean free;

    public Builder() {
    }

    /**
     * / 無料
     */
    public Builder free(Boolean free) {
      this.free = free;
      return this;
    }

    @Override
    public VideoProgramLabel build() {
      return new VideoProgramLabel(free, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_VideoProgramLabel extends ProtoAdapter<VideoProgramLabel> {
    ProtoAdapter_VideoProgramLabel() {
      super(FieldEncoding.LENGTH_DELIMITED, VideoProgramLabel.class);
    }

    @Override
    public int encodedSize(VideoProgramLabel value) {
      return (value.free != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.free) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, VideoProgramLabel value) throws IOException {
      if (value.free != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.free);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public VideoProgramLabel decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.free(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public VideoProgramLabel redact(VideoProgramLabel value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
