// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/video_feature.proto at 34:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * / ビデオカードラベル
 */
public final class VideoCardLabel extends Message<VideoCardLabel, VideoCardLabel.Builder> {
  public static final ProtoAdapter<VideoCardLabel> ADAPTER = new ProtoAdapter_VideoCardLabel();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_FREE = false;

  public static final Boolean DEFAULT_SOMEFREE = false;

  public static final Boolean DEFAULT_HOT = false;

  /**
   * / 無料
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean free;

  /**
   * / 一部無料
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean someFree;

  /**
   * / 注目
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean hot;

  public VideoCardLabel(Boolean free, Boolean someFree, Boolean hot) {
    this(free, someFree, hot, ByteString.EMPTY);
  }

  public VideoCardLabel(Boolean free, Boolean someFree, Boolean hot, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.free = free;
    this.someFree = someFree;
    this.hot = hot;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.free = free;
    builder.someFree = someFree;
    builder.hot = hot;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof VideoCardLabel)) return false;
    VideoCardLabel o = (VideoCardLabel) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(free, o.free)
        && Internal.equals(someFree, o.someFree)
        && Internal.equals(hot, o.hot);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (free != null ? free.hashCode() : 0);
      result = result * 37 + (someFree != null ? someFree.hashCode() : 0);
      result = result * 37 + (hot != null ? hot.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (free != null) builder.append(", free=").append(free);
    if (someFree != null) builder.append(", someFree=").append(someFree);
    if (hot != null) builder.append(", hot=").append(hot);
    return builder.replace(0, 2, "VideoCardLabel{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<VideoCardLabel, Builder> {
    public Boolean free;

    public Boolean someFree;

    public Boolean hot;

    public Builder() {
    }

    /**
     * / 無料
     */
    public Builder free(Boolean free) {
      this.free = free;
      return this;
    }

    /**
     * / 一部無料
     */
    public Builder someFree(Boolean someFree) {
      this.someFree = someFree;
      return this;
    }

    /**
     * / 注目
     */
    public Builder hot(Boolean hot) {
      this.hot = hot;
      return this;
    }

    @Override
    public VideoCardLabel build() {
      return new VideoCardLabel(free, someFree, hot, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_VideoCardLabel extends ProtoAdapter<VideoCardLabel> {
    ProtoAdapter_VideoCardLabel() {
      super(FieldEncoding.LENGTH_DELIMITED, VideoCardLabel.class);
    }

    @Override
    public int encodedSize(VideoCardLabel value) {
      return (value.free != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.free) : 0)
          + (value.someFree != null ? ProtoAdapter.BOOL.encodedSizeWithTag(2, value.someFree) : 0)
          + (value.hot != null ? ProtoAdapter.BOOL.encodedSizeWithTag(3, value.hot) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, VideoCardLabel value) throws IOException {
      if (value.free != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.free);
      if (value.someFree != null) ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.someFree);
      if (value.hot != null) ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.hot);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public VideoCardLabel decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.free(ProtoAdapter.BOOL.decode(reader)); break;
          case 2: builder.someFree(ProtoAdapter.BOOL.decode(reader)); break;
          case 3: builder.hot(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public VideoCardLabel redact(VideoCardLabel value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
