// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/video_viewing.proto at 46:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * / ビデオ視聴コンテンツVOD
 */
public final class VideoViewingContentVOD extends Message<VideoViewingContentVOD, VideoViewingContentVOD.Builder> {
  public static final ProtoAdapter<VideoViewingContentVOD> ADAPTER = new ProtoAdapter_VideoViewingContentVOD();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_ID = "";

  public static final Long DEFAULT_DURATION = 0L;

  public static final String DEFAULT_THUMBIMAGE = "";

  public static final Long DEFAULT_IMAGEUPDATEDAT = 0L;

  public static final String DEFAULT_TITLE = "";

  public static final String DEFAULT_SERIESTITLE = "";

  public static final Long DEFAULT_ENDAT = 0L;

  public static final Long DEFAULT_FREEENDAT = 0L;

  /**
   * / プログラムID
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String id;

  /**
   * / 本編尺（秒）
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long duration;

  /**
   * / サムネイル画像
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String thumbImage;

  /**
   * / シーンサムネイル画像一覧
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REPEATED
  )
  public final List<String> sceneThumbImages;

  /**
   * / 画像最終更新UNIX時間
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long imageUpdatedAt;

  /**
   * / タイトル
   */
  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String title;

  /**
   * / シリーズタイトル
   */
  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String seriesTitle;

  /**
   * / 公開終了UINX時間
   */
  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long endAt;

  /**
   * / 無料公開終了UINX時間（無料公開期間中に限りセットされる）
   */
  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long freeEndAt;

  public VideoViewingContentVOD(String id, Long duration, String thumbImage, List<String> sceneThumbImages, Long imageUpdatedAt, String title, String seriesTitle, Long endAt, Long freeEndAt) {
    this(id, duration, thumbImage, sceneThumbImages, imageUpdatedAt, title, seriesTitle, endAt, freeEndAt, ByteString.EMPTY);
  }

  public VideoViewingContentVOD(String id, Long duration, String thumbImage, List<String> sceneThumbImages, Long imageUpdatedAt, String title, String seriesTitle, Long endAt, Long freeEndAt, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.duration = duration;
    this.thumbImage = thumbImage;
    this.sceneThumbImages = Internal.immutableCopyOf("sceneThumbImages", sceneThumbImages);
    this.imageUpdatedAt = imageUpdatedAt;
    this.title = title;
    this.seriesTitle = seriesTitle;
    this.endAt = endAt;
    this.freeEndAt = freeEndAt;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.duration = duration;
    builder.thumbImage = thumbImage;
    builder.sceneThumbImages = Internal.copyOf("sceneThumbImages", sceneThumbImages);
    builder.imageUpdatedAt = imageUpdatedAt;
    builder.title = title;
    builder.seriesTitle = seriesTitle;
    builder.endAt = endAt;
    builder.freeEndAt = freeEndAt;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof VideoViewingContentVOD)) return false;
    VideoViewingContentVOD o = (VideoViewingContentVOD) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(duration, o.duration)
        && Internal.equals(thumbImage, o.thumbImage)
        && Internal.equals(sceneThumbImages, o.sceneThumbImages)
        && Internal.equals(imageUpdatedAt, o.imageUpdatedAt)
        && Internal.equals(title, o.title)
        && Internal.equals(seriesTitle, o.seriesTitle)
        && Internal.equals(endAt, o.endAt)
        && Internal.equals(freeEndAt, o.freeEndAt);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (duration != null ? duration.hashCode() : 0);
      result = result * 37 + (thumbImage != null ? thumbImage.hashCode() : 0);
      result = result * 37 + (sceneThumbImages != null ? sceneThumbImages.hashCode() : 1);
      result = result * 37 + (imageUpdatedAt != null ? imageUpdatedAt.hashCode() : 0);
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (seriesTitle != null ? seriesTitle.hashCode() : 0);
      result = result * 37 + (endAt != null ? endAt.hashCode() : 0);
      result = result * 37 + (freeEndAt != null ? freeEndAt.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (duration != null) builder.append(", duration=").append(duration);
    if (thumbImage != null) builder.append(", thumbImage=").append(thumbImage);
    if (sceneThumbImages != null) builder.append(", sceneThumbImages=").append(sceneThumbImages);
    if (imageUpdatedAt != null) builder.append(", imageUpdatedAt=").append(imageUpdatedAt);
    if (title != null) builder.append(", title=").append(title);
    if (seriesTitle != null) builder.append(", seriesTitle=").append(seriesTitle);
    if (endAt != null) builder.append(", endAt=").append(endAt);
    if (freeEndAt != null) builder.append(", freeEndAt=").append(freeEndAt);
    return builder.replace(0, 2, "VideoViewingContentVOD{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<VideoViewingContentVOD, Builder> {
    public String id;

    public Long duration;

    public String thumbImage;

    public List<String> sceneThumbImages;

    public Long imageUpdatedAt;

    public String title;

    public String seriesTitle;

    public Long endAt;

    public Long freeEndAt;

    public Builder() {
      sceneThumbImages = Internal.newMutableList();
    }

    /**
     * / プログラムID
     */
    public Builder id(String id) {
      this.id = id;
      return this;
    }

    /**
     * / 本編尺（秒）
     */
    public Builder duration(Long duration) {
      this.duration = duration;
      return this;
    }

    /**
     * / サムネイル画像
     */
    public Builder thumbImage(String thumbImage) {
      this.thumbImage = thumbImage;
      return this;
    }

    /**
     * / シーンサムネイル画像一覧
     */
    public Builder sceneThumbImages(List<String> sceneThumbImages) {
      Internal.checkElementsNotNull(sceneThumbImages);
      this.sceneThumbImages = sceneThumbImages;
      return this;
    }

    /**
     * / 画像最終更新UNIX時間
     */
    public Builder imageUpdatedAt(Long imageUpdatedAt) {
      this.imageUpdatedAt = imageUpdatedAt;
      return this;
    }

    /**
     * / タイトル
     */
    public Builder title(String title) {
      this.title = title;
      return this;
    }

    /**
     * / シリーズタイトル
     */
    public Builder seriesTitle(String seriesTitle) {
      this.seriesTitle = seriesTitle;
      return this;
    }

    /**
     * / 公開終了UINX時間
     */
    public Builder endAt(Long endAt) {
      this.endAt = endAt;
      return this;
    }

    /**
     * / 無料公開終了UINX時間（無料公開期間中に限りセットされる）
     */
    public Builder freeEndAt(Long freeEndAt) {
      this.freeEndAt = freeEndAt;
      return this;
    }

    @Override
    public VideoViewingContentVOD build() {
      return new VideoViewingContentVOD(id, duration, thumbImage, sceneThumbImages, imageUpdatedAt, title, seriesTitle, endAt, freeEndAt, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_VideoViewingContentVOD extends ProtoAdapter<VideoViewingContentVOD> {
    ProtoAdapter_VideoViewingContentVOD() {
      super(FieldEncoding.LENGTH_DELIMITED, VideoViewingContentVOD.class);
    }

    @Override
    public int encodedSize(VideoViewingContentVOD value) {
      return (value.id != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.id) : 0)
          + (value.duration != null ? ProtoAdapter.INT64.encodedSizeWithTag(2, value.duration) : 0)
          + (value.thumbImage != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.thumbImage) : 0)
          + ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(4, value.sceneThumbImages)
          + (value.imageUpdatedAt != null ? ProtoAdapter.INT64.encodedSizeWithTag(5, value.imageUpdatedAt) : 0)
          + (value.title != null ? ProtoAdapter.STRING.encodedSizeWithTag(6, value.title) : 0)
          + (value.seriesTitle != null ? ProtoAdapter.STRING.encodedSizeWithTag(7, value.seriesTitle) : 0)
          + (value.endAt != null ? ProtoAdapter.INT64.encodedSizeWithTag(8, value.endAt) : 0)
          + (value.freeEndAt != null ? ProtoAdapter.INT64.encodedSizeWithTag(9, value.freeEndAt) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, VideoViewingContentVOD value) throws IOException {
      if (value.id != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id);
      if (value.duration != null) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.duration);
      if (value.thumbImage != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.thumbImage);
      if (value.sceneThumbImages != null) ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.sceneThumbImages);
      if (value.imageUpdatedAt != null) ProtoAdapter.INT64.encodeWithTag(writer, 5, value.imageUpdatedAt);
      if (value.title != null) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.title);
      if (value.seriesTitle != null) ProtoAdapter.STRING.encodeWithTag(writer, 7, value.seriesTitle);
      if (value.endAt != null) ProtoAdapter.INT64.encodeWithTag(writer, 8, value.endAt);
      if (value.freeEndAt != null) ProtoAdapter.INT64.encodeWithTag(writer, 9, value.freeEndAt);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public VideoViewingContentVOD decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.duration(ProtoAdapter.INT64.decode(reader)); break;
          case 3: builder.thumbImage(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.sceneThumbImages.add(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.imageUpdatedAt(ProtoAdapter.INT64.decode(reader)); break;
          case 6: builder.title(ProtoAdapter.STRING.decode(reader)); break;
          case 7: builder.seriesTitle(ProtoAdapter.STRING.decode(reader)); break;
          case 8: builder.endAt(ProtoAdapter.INT64.decode(reader)); break;
          case 9: builder.freeEndAt(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public VideoViewingContentVOD redact(VideoViewingContentVOD value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
