// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api/search.proto at 25:1
package tv.abema.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * / VideoProgramSearchResponse represents a response of getting search result of video program.
 */
public final class VideoProgramSearchResponse extends Message<VideoProgramSearchResponse, VideoProgramSearchResponse.Builder> {
  public static final ProtoAdapter<VideoProgramSearchResponse> ADAPTER = new ProtoAdapter_VideoProgramSearchResponse();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_COUNT = 0L;

  /**
   * programs
   */
  @WireField(
      tag = 1,
      adapter = "tv.abema.protos.VideoProgram#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<VideoProgram> programs;

  /**
   * / Total count
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long count;

  public VideoProgramSearchResponse(List<VideoProgram> programs, Long count) {
    this(programs, count, ByteString.EMPTY);
  }

  public VideoProgramSearchResponse(List<VideoProgram> programs, Long count, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.programs = Internal.immutableCopyOf("programs", programs);
    this.count = count;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.programs = Internal.copyOf("programs", programs);
    builder.count = count;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof VideoProgramSearchResponse)) return false;
    VideoProgramSearchResponse o = (VideoProgramSearchResponse) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(programs, o.programs)
        && Internal.equals(count, o.count);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (programs != null ? programs.hashCode() : 1);
      result = result * 37 + (count != null ? count.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (programs != null) builder.append(", programs=").append(programs);
    if (count != null) builder.append(", count=").append(count);
    return builder.replace(0, 2, "VideoProgramSearchResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<VideoProgramSearchResponse, Builder> {
    public List<VideoProgram> programs;

    public Long count;

    public Builder() {
      programs = Internal.newMutableList();
    }

    /**
     * programs
     */
    public Builder programs(List<VideoProgram> programs) {
      Internal.checkElementsNotNull(programs);
      this.programs = programs;
      return this;
    }

    /**
     * / Total count
     */
    public Builder count(Long count) {
      this.count = count;
      return this;
    }

    @Override
    public VideoProgramSearchResponse build() {
      return new VideoProgramSearchResponse(programs, count, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_VideoProgramSearchResponse extends ProtoAdapter<VideoProgramSearchResponse> {
    ProtoAdapter_VideoProgramSearchResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, VideoProgramSearchResponse.class);
    }

    @Override
    public int encodedSize(VideoProgramSearchResponse value) {
      return VideoProgram.ADAPTER.asRepeated().encodedSizeWithTag(1, value.programs)
          + (value.count != null ? ProtoAdapter.INT64.encodedSizeWithTag(2, value.count) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, VideoProgramSearchResponse value) throws IOException {
      if (value.programs != null) VideoProgram.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.programs);
      if (value.count != null) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.count);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public VideoProgramSearchResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.programs.add(VideoProgram.ADAPTER.decode(reader)); break;
          case 2: builder.count(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public VideoProgramSearchResponse redact(VideoProgramSearchResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.programs, VideoProgram.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
